import { create } from 'zustand';

export const useGameStore = create((set) => ({
  room: null,
  roomId: '',
  roomCode: '',
  gameType: 'CARROM',
  phase: 'WAITING',
  turnIndex: 0,
  turnNo: 1,
  winnerUserId: '',
  statusMessage: 'Waiting for players',
  targetScore: 0,
  diceValue: 0,
  safeZones: [],
  movableTokenIds: [],
  players: [],
  playerScores: {},
  ludoPlayers: [],
  pulse: 0,
  setRoomMeta: ({ roomId, roomCode }) => set({ roomId, roomCode }),
  setRoom: (room) => set({ room }),
  setStateSnapshot: (snap) => set({
    gameType: snap.gameType,
    phase: snap.phase,
    turnIndex: snap.turnIndex,
    turnNo: snap.turnNo,
    winnerUserId: snap.winnerUserId,
    statusMessage: snap.statusMessage,
    targetScore: snap.targetScore,
    diceValue: snap.diceValue,
    safeZones: snap.safeZones,
    movableTokenIds: snap.movableTokenIds,
    players: snap.players,
    playerScores: snap.playerScores,
    ludoPlayers: snap.ludoPlayers
  }),
  setPulse: (pulse) => set({ pulse }),
  reset: () => set({
    room: null,
    roomId: '',
    roomCode: '',
    gameType: 'CARROM',
    phase: 'WAITING',
    turnIndex: 0,
    turnNo: 1,
    winnerUserId: '',
    statusMessage: 'Waiting for players',
    targetScore: 0,
    diceValue: 0,
    safeZones: [],
    movableTokenIds: [],
    players: [],
    playerScores: {},
    ludoPlayers: [],
    pulse: 0
  })
}));
